// Divine Hub weekly content (2026-09-28). Source comparison: Green Message and Shlokam.org.
// Aparajita Stotram: Devi Mahatmyam chapter 5, all 28 verses of this familiar excerpt.
const PRAYERS5 = [
{
  id: 'devi-aparajita-stotram',
  title: 'Devi Aparajita Stotram (Ya Devi Sarva Bhuteshu)',
  titleDev: 'देवी अपराजिता स्तोत्रम् — या देवी सर्वभूतेषु',
  deity: 'Durga', deityDev: 'दुर्गा', type: 'Stotram', lang: 'sa',
  about: 'The 28-verse praise of the unconquered Goddess from chapter five of the Devi Mahatmyam. It sees the Divine Mother in consciousness, discernment, sleep, hunger, power, patience, peace and compassion throughout creation. Presented as a complete stotram excerpt, not the full Devi Mahatmyam, for recitation before Sharad Navratri.',
  keywords: ['durga', 'devi', 'aparajita', 'ya devi sarva bhuteshu', 'namastasyai', 'shakti', 'navratri', 'devi mahatmyam', 'japa', 'stotram'],
  stanzas: [
    {"dev": ["नमो देव्यै महादेव्यै शिवायै सततं नमः ।", "नमः प्रकृत्यै भद्रायै नियताः प्रणताः स्म ताम्॥ १॥"], "translit": ["Namo devyai mahaadevyai shivaayai satatam namah.", "Namah prakrityai bhadrayai niyatah pranatah sma tam."], "meaning": "Salutations to the Goddess, the Great Goddess, auspicious Shiva, the primal nature and the gracious one. We bow before her again and again."},
    {"dev": ["रौद्रायै नमो नित्यायै गौर्यै धात्र्यै नमो नमः ।", "ज्योत्स्नायै चेन्दुरूपिण्यै सुखायै सततं नमः॥ २॥"], "translit": ["Raudraayai namo nityaayai gauryai dhaatryai namo namah.", "jyotsnaayai chenduruupinyai sukhaayai satatam namah."], "meaning": "Salutations to her as the fierce and eternal one, the radiant Gauri, the sustaining mother, moonlight and happiness."},
    {"dev": ["कल्याण्यै प्रणता वृद्ध्यै सिद्ध्यै कुर्मो नमो नमः ।", "नैरृत्यै भूभृतां लक्ष्म्यै शर्वाण्यै ते नमो नमः॥ ३॥"], "translit": ["Kalyaanyai pranataa vriddhyai siddhyai kurmo namo namah.", "nairrityai bhuubhritaam lakshmyai sharvaanyai te namo namah."], "meaning": "We bow to her as auspiciousness, growth and accomplishment; as the power that can dissolve and the fortune that upholds the earth; as the consort of Shiva."},
    {"dev": ["दुर्गायै दुर्गपारायै सारायै सर्वकारिण्यै ।", "ख्यात्यै तथैव कृष्णायै धूम्रायै सततं नमः॥ ४॥"], "translit": ["Durgaayai durgapaaraayai saaraayai sarvakaarinyai.", "khyaatyai tathaiva krishnaayai dhuumraayai satatam namah."], "meaning": "Salutations to Durga, who carries us across difficulties; to the essence and doer of all, renowned, dark and mysterious."},
    {"dev": ["अतिसौम्यातिरौद्रायै नतास्तस्यै नमो नमः ।", "नमो जगत्प्रतिष्ठायै देव्यै कृत्यै नमो नमः॥ ५॥"], "translit": ["Atisaumyaatiraudraayai nataastasyai namo namah.", "namo jagatpratishthaayai devyai krityai namo namah."], "meaning": "We bow to her who is both exceedingly gentle and fierce, the ground of the universe and the power that brings things into being."},
    {"dev": ["या देवी सर्वभूतेषु विष्णुमायेति शब्दिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ ६॥"], "translit": ["Yaa devii sarvabhuuteshu vishnumaayeti shabditaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as Vishnumaya, the divine power that pervades all beings: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु चेतनेत्यभिधीयते ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ ७॥"], "translit": ["Yaa devii sarvabhuuteshu chetanetyabhidhiiyate.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as consciousness in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु बुद्धिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ ८॥"], "translit": ["Yaa devii sarvabhuuteshu buddhiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as discernment and intelligence in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु निद्रारूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ ९॥"], "translit": ["Yaa devii sarvabhuuteshu nidraaruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as sleep in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु क्षुधारूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ १०॥"], "translit": ["Yaa devii sarvabhuuteshu kshudhaaruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as hunger in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु छायारूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ ११॥"], "translit": ["Yaa devii sarvabhuuteshu chaayaaruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as the shadow or reflection in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ १२॥"], "translit": ["Yaa devii sarvabhuuteshu shaktiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as power in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु तृष्णारूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ १३॥"], "translit": ["Yaa devii sarvabhuuteshu trishnaaruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as thirst and longing in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु क्षान्तिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ १४॥"], "translit": ["Yaa devii sarvabhuuteshu kshaantiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as forbearance in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु जातिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ १५॥"], "translit": ["Yaa devii sarvabhuuteshu jaatiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as the diversity of birth and kind in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु लज्जारूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ १६॥"], "translit": ["Yaa devii sarvabhuuteshu lajjaaruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as modesty in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु शान्तिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ १७॥"], "translit": ["Yaa devii sarvabhuuteshu shaantiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as peace in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु श्रद्धारूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ १८॥"], "translit": ["Yaa devii sarvabhuuteshu shraddhaaruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as faith in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु कान्तिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ १९॥"], "translit": ["Yaa devii sarvabhuuteshu kaantiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as beauty and radiance in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु लक्ष्मीरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ २०॥"], "translit": ["Yaa devii sarvabhuuteshu lakshmiiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as good fortune in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु वृत्तिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ २१॥"], "translit": ["Yaa devii sarvabhuuteshu vrittiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as the force of activity and livelihood in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु स्मृतिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ २२॥"], "translit": ["Yaa devii sarvabhuuteshu smritiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as memory in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु दयारूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ २३॥"], "translit": ["Yaa devii sarvabhuuteshu dayaaruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as compassion in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु तुष्टिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ २४॥"], "translit": ["Yaa devii sarvabhuuteshu tushtiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as contentment in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु मातृरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ २५॥"], "translit": ["Yaa devii sarvabhuuteshu maatriruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as the mother in every being: salutations to her, again and again."},
    {"dev": ["या देवी सर्वभूतेषु भ्रान्तिरूपेण संस्थिता ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ २६॥"], "translit": ["Yaa devii sarvabhuuteshu bhraantiruupena samsthitaa.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "To the Goddess who dwells as delusion in every being: salutations to her, again and again."},
    {"dev": ["इन्द्रियाणामधिष्ठात्री भूतानां चाखिलेषु या ।", "भूतेषु सततं तस्यै व्याप्त्यै देव्यै नमो नमः॥ २७॥"], "translit": ["Indriyaanaamadhishthaatrii bhuutaanaam chaakhileshu yaa.", "bhuuteshu satatam tasyai vyaaptyai devyai namo namah."], "meaning": "Salutations to the Goddess who presides over the senses and continually pervades all beings."},
    {"dev": ["चितिरूपेण या कृत्स्नमेतद् व्याप्य स्थिता जगत् ।", "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥ २८॥"], "translit": ["Chitiruupena yaa kritsnametad vyaapya sthitaa jagat.", "namastasyai namastasyai namastasyai namo namah."], "meaning": "Salutations again and again to the Goddess who, as consciousness, pervades the entire world."}
  ]
},
{
  id: 'durga-bija-mantra',
  title: 'Durga Bija Mantra', titleDev: 'दुर्गा बीज मन्त्र',
  deity: 'Durga', deityDev: 'दुर्गा', type: 'Mantra', lang: 'sa',
  about: 'A concise, widely recited invocation of Durga for japa. “Dum” is her bija, or seed syllable; it is not a word with a literal English translation. A simple form to take into a quiet daily practice, especially in the lead-up to Navratri.',
  keywords: ['durga', 'dum', 'durgayai', 'bija', 'beej', 'mantra', 'japa', 'navratri', 'mala'],
  stanzas: [{ dev: ['ॐ दुं दुर्गायै नमः॥'], translit: ['Om dum Durgayai namah.'], meaning: 'Om. Salutations to Durga. “Dum” is her traditional seed syllable, a sacred sound rather than a word to translate literally.' }]
}
];
if (typeof PRAYERS !== 'undefined') PRAYERS.push(...PRAYERS5);
