// Divine Hub — "Why is this used in puja?" reference database
// Symmetric entries: role (what it is for), traditional (the sacred reason),
// science (the practical reason, where one is traditionally cited).
// Claims kept to widely accepted tradition and mainstream practical knowledge.

const WHY_CATEGORIES = [
  {
    id: 'powders-pastes',
    title: 'Powders & Pastes',
    dev: 'चूर्ण और लेप',
    items: [
      { item: 'Kumkum / Roli', dev: 'कुमकुम / रोली', role: 'Red powder applied as tilak on the deity and on the forehead of worshippers.', traditional: 'Red is the colour of shakti — auspicious energy and the married state. The tilak marks the ajna chakra, the seat of awareness, and receiving it means carrying the deity’s blessing on your body.', science: 'Traditional kumkum is turmeric slaked with lime; turmeric is antiseptic. The forehead point sits over a dense nerve plexus, and gentle pressure there is calming.' },
      { item: 'Haldi (Turmeric)', dev: 'हल्दी', role: 'Yellow powder offered to the deity, mixed in ritual water, and used in every auspicious rite.', traditional: 'Yellow belongs to Vishnu and to prosperity; turmeric is considered mangal (auspicious) itself. Ganesh is especially worshipped with haldi — a whole turmeric root can stand in as His murti.', science: 'Turmeric is a documented antiseptic and anti-inflammatory (curcumin). Ritual water and pastes made with it stay cleaner longer.' },
      { item: 'Chandan (Sandalwood paste)', dev: 'चंदन', role: 'Cooling paste applied as tilak, especially to Shiva, Vishnu and Hanuman.', traditional: 'Sandal is beloved of the gods and is called cool like the moon; applying it invokes serenity. A chandan tilak signifies a mind cooled of anger and desire.', science: 'Sandalwood paste is genuinely cooling on the skin and mildly antimicrobial; its fragrance is used in aromatherapy for calming.' },
      { item: 'Vibhuti / Bhasma (Sacred ash)', dev: 'विभूति / भस्म', role: 'Ash smeared on the forehead in three lines by Shiva devotees.', traditional: 'Ash is what remains when everything transient burns — it reminds the wearer of impermanence and is Shiva’s own ornament. The three lines stand for the removal of the three impurities: ego, karma and illusion.', science: 'Clean vibhuti is prepared from burnt cow dung cakes in yajna; it is alkaline and mildly antiseptic on skin.' },
      { item: 'Sindoor', dev: 'सिंदूर', role: 'Bright red-orange powder offered to Hanuman and worn by married women.', traditional: 'Hanuman covered Himself in sindoor so that Rama would live long — since then sindoor offered to Him is returned as strength and protection. In a woman’s maang it signifies her husband’s wellbeing.', science: 'Classical sindoor was made from turmeric, lime and herbs. Modern cosmetic versions should be lead-free; the ritual point, not the chemistry, is the sacred part.' },
      { item: 'Kesar (Saffron)', dev: 'केसर', role: 'Precious orange-red threads offered in tilak, panchamrit and bhog.', traditional: 'Saffron is the colour of sacrifice and tapas — the robes of sannyasis. Offering the costliest spice says: the best belongs to God.', science: 'Saffron is a known antioxidant and mood-lifting spice; a few threads richly fragrance milk-based prasad.' },
      { item: 'Ashtagandha', dev: 'अष्टगंध', role: 'A blend of eight fragrant substances used for deity tilak on special occasions.', traditional: 'The eight fragrances (sandal, agar, camphor, saffron and others by regional recipe) together are considered a complete offering of scent to the deity.', science: 'The blend layers several aromatic resins and spices, each individually antimicrobial; the combined fragrance is long-lasting.' },
      { item: 'Multani mitti / ritual clay', dev: 'पूजा की मिट्टी', role: 'Clean earth used to sanctify the puja platform and make temporary murtis.', traditional: 'Earth is the mother and the first element; Ganesh murtis for Chaturthi are made of clay so they can return to water at visarjan.', science: 'Shadu clay dissolves harmlessly in water — the basis of the eco-friendly visarjan tradition, unlike plaster-of-paris which pollutes.' }
    ]
  },
  {
    id: 'flames-fragrances',
    title: 'Flames & Fragrances',
    dev: 'ज्योति और सुगंध',
    items: [
      { item: 'Diya (Oil/Ghee lamp)', dev: 'दीपक', role: 'The flame offered to the deity and kept lit through the puja.', traditional: 'The diya is the symbol of the inner light of knowledge dispelling the darkness of ignorance; offering light to the Light of the world is the heart of aarti. Ghee lamps are sattvic, sesame-oil lamps pacifying.', science: 'A steady flame fixes the gaze and settles the mind — the practical basis of tratak meditation. Ghee and sesame flames burn clean and warm the space gently.' },
      { item: 'Camphor (Kapoor)', dev: 'कपूर', role: 'Burned in the aarti flame at the close of puja.', traditional: 'Camphor burns without residue — the symbol of the ego that should vanish entirely into the divine, leaving nothing behind. Its white flame is considered pure enough for the deity’s face.', science: 'Camphor ignites completely (sublimation), leaving no soot on the offering plate; its strong aroma is naturally antimicrobial and repels insects in the prayer space.' },
      { item: 'Agarbatti (Incense stick)', dev: 'अगरबत्ती', role: 'Fragrant smoke offered continuously during puja.', traditional: 'Fragrance (gandha) is one of the five cosmic elements offered in panchopachar puja; smoke rising is the visible sign of prayer ascending.', science: 'Sandal and floral incense mask odours and mark the space; natural-ingredient sticks are preferred — heavy synthetic smoke irritates, so ventilate.' },
      { item: 'Dhoop', dev: 'धूप', role: 'Thick resin incense (loban, guggal, sambrani) waved after aarti.', traditional: 'Dhoop is the denser, earthier offering of fragrance, used to pervade the whole room and invite the deity’s presence; loban smoke is traditional in Bengali and temple aartis.', science: 'Benzoin (loban) and guggal resins have documented antimicrobial smoke; fumigating closed rooms with resin smoke was a household hygiene practice.' },
      { item: 'Guggal', dev: 'गुग्गल', role: 'Golden resin burned on coals, especially in havan and evening aarti.', traditional: 'Guggal is dear to the Goddess; its smoke is said to drive away negative influences and purify the home’s energy.', science: 'Guggul (Commiphora) resin is a recognised Ayurvedic substance (guggulipid); its aromatic smoke disinfects and repels pests.' },
      { item: 'Ittar / Rose water', dev: 'इत्र / गुलाब जल', role: 'A drop of fragrance offered to the deity and sprinkled on devotees.', traditional: 'Scent is the subtlest gift; offering ittar honours the deity as an honoured guest, and sprinkling rose water closes the puja by blessing everyone present.', science: 'Natural rose water is a mild, safe skin freshener; the cool sprinkle at the end refreshes after a long sitting.' }
    ]
  },
  {
    id: 'offerings-food',
    title: 'Offerings & Food',
    dev: 'नैवेद्य',
    items: [
      { item: 'Panchamrit', dev: 'पंचामृत', role: 'The five-nectar mixture (milk, curd, ghee, honey, sugar) used to bathe the deity.', traditional: 'The five nectars represent the five elements harmonised in offering; bathing the murti in them is the highest act of hospitality to God as guest. The used panchamrit is taken as charnamrit — the most blessed prasad.', science: 'Each ingredient is a preservative or nutrient; mixed in small quantity and shared immediately, it is a rich, energy-dense sacred food.' },
      { item: 'Akshat (Unbroken rice)', dev: 'अक्षत', role: 'Whole rice grains offered at every invocation and blessing.', traditional: 'Rice that is whole (akshat = unbroken) stands for wholeness and prosperity; it is the seed of sustenance and is placed on the kalash, the deity and the heads of the blessed.', science: 'Rice is the staple grain of India — offering it symbolically offers the entire food supply; whole unbroken grains keep without spoiling.' },
      { item: 'Coconut', dev: 'नारियल', role: 'Offered whole on the kalash and broken as bhog.', traditional: 'The coconut is called shriphal — the fruit of the Goddess — and is a substitute for the ancient idea of the most precious offering; its three eyes stand for Shiva’s trinetra. Breaking it symbolises breaking the ego (the hard shell) to reveal purity within.', science: 'Coconut is a complete food (water, fat, fibre); a whole coconut travels and stores well, making it the practical sacred offering across India.' },
      { item: 'Paan (Betel leaf)', dev: 'पान', role: 'Betel leaf offered with supari at the close of worship.', traditional: 'Paan completes the meal offered to the deity as a digestive and mouth-freshener, honouring God as a guest fed to satisfaction. It is also offered to Ganesh and in every aarti thali.', science: 'Betel leaf is a genuine digestive and mild antiseptic; chewed after meals it stimulates saliva and freshens breath.' },
      { item: 'Supari (Betel nut)', dev: 'सुपारी', role: 'Areca nut placed in the kalash, used as deity seats in some rites, and given in dakshina.', traditional: 'Supari stands for firmness of resolve; because it is hard and enduring it is also used as a portable symbol of Ganesh and of the witness of the vow.', science: 'Areca nut keeps for years without spoiling, making it a practical ritual token — though as a habit its chewing is a health risk, so it is offered, not consumed.' },
      { item: 'Honey', dev: 'शहद', role: 'One of the five nectars of panchamrit; offered in abhishek.', traditional: 'Honey is madhu — sweetness itself; offering it asks that life and speech be sweet. It is essential in Shiva abhishek and in panchamrit.', science: 'Honey is naturally antibacterial and never spoils — a fitting symbol of incorruptibility.' },
      { item: 'Milk & Curd (Dahi)', dev: 'दूध और दही', role: 'Abhishek liquids and base of panchamrit; curd-rice eaten before auspicious departures.', traditional: 'Milk is the gift of the cow, the symbol of nurturing motherly grace; Shiva’s abhishek with milk cools the fiery Lord. Curd eaten before a journey is the household blessing for success.', science: 'Milk and curd are complete foods; the custom of a curd mouthful before travel is a gentle pre-journey settle of the stomach.' },
      { item: 'Ghee', dev: 'घी', role: 'Fuel of the sacred flame and an oblation poured into havan fire.', traditional: 'Ghee is the essence of milk, hence the essence of nourishment; poured into fire it becomes the carrier that takes offerings to the gods in Vedic ritual.', science: 'Ghee has a high smoke point and feeds a bright, low-soot flame; in havan quantities it combusts fully, producing a clean fragrant fire.' },
      { item: 'Kheel-Batasha / Mishri', dev: 'खील-बटाशा / मिश्री', role: 'Puffed rice and sugar drops offered especially to Lakshmi and at Satyanarayan puja.', traditional: 'Light puffed rice and pure sugar are sattvic sweetness; batasha is the traditional prasad of gratitude after a vow is fulfilled.', science: 'Puffed rice and crystallised sugar are dry, long-keeping prasad foods that distribute hygienically to large gatherings.' },
      { item: 'Modak & Laddu', dev: 'मोदक और लड्डू', role: 'The beloved sweets of Ganesh, offered in counts of 21.', traditional: 'The modak’s sweet core hidden in a plain shell symbolises the bliss of the soul within the body; Ganesh’s love for modaks is celebrated in the name Modakapriya (He who loves modak).', science: 'Steamed ukadiche modak (rice shell, jaggery-coconut filling) is a light, cooked sweet that keeps well through the festival.' },
      { item: 'Gur-Chana (Jaggery & roasted gram)', dev: 'गुड़-चना', role: 'The simple offering of Santoshi Maa’s Friday vrat and of Hanuman.', traditional: 'The vow of Santoshi Maa is kept with the humblest food — jaggery and roasted gram — and sour food is avoided; the lesson is contentment with simplicity. Hanuman too is pleased by chana and jaggery.', science: 'Jaggery plus roasted gram is a balanced iron-and-protein fast food — sustaining through a day of vrat on minimal cost.' },
      { item: 'Charanamrit', dev: 'चरणामृत', role: 'The sanctified liquid (often the used panchamrit or tulsi water) sipped after puja.', traditional: 'It is the water that has touched the deity’s feet — receiving it is receiving grace itself; tulsi leaves in it make it Vishnu’s own blessing.', science: 'Tulsi-infused water carries the herb’s aromatic oils; sipped in a spoonful it is a calming ritual close to the meal of worship.' }
    ]
  },
  {
    id: 'leaves-flowers-fruits',
    title: 'Leaves, Flowers & Fruits',
    dev: 'पत्र, पुष्प और फल',
    items: [
      { item: 'Tulsi (Holy basil)', dev: 'तुलसी', role: 'Sacred leaf essential to every offering for Vishnu and Krishna.', traditional: 'Tulsi is the Goddess Tulsi, beloved of Vishnu — no bhog is accepted by Him without a tulsi leaf touching it. By tradition tulsi is NOT offered to Ganesh (the legend of their mutual curse) nor to Shiva lingam by many schools.', science: 'Tulsi (Ocimum tenuiflorum) is a documented adaptogen and antimicrobial herb; a leaf in the offering water keeps it fresh.' },
      { item: 'Bel patra (Bilva leaf)', dev: 'बेल पत्र', role: 'The three-lobed leaf essential to Shiva worship.', traditional: 'The three leaflets are the three eyes of Shiva, or the trishul, or Brahma-Vishnu-Mahesh in one; offering bel patra cools and pleases Shiva above all other leaves.', science: 'Bael (Aegle marmelos) leaves are aromatic and traditionally medicinal (digestive, cooling); the tree is sacred across Shiva temples.' },
      { item: 'Durva grass', dev: 'दूर्वा', role: 'Bunches of 21 blades offered to Ganesh.', traditional: 'When the demon Analasur’s heat scorched the worlds, Ganesh swallowed him and was cooled by durva laid on His head — since then durva is His most beloved offering, given in odd counts of 21.', science: 'Durva (Cynodon dactylon) is a hardy coolant herb of Ayurveda; its fresh blades stay green long after picking, suiting festival-long worship.' },
      { item: 'Datura', dev: 'धतूरा', role: 'The white thorn-apple flower and fruit offered only to Shiva.', traditional: 'Datura is the poison-flower that only Shiva — the drinker of halahal poison — can receive; offering it remembers His drinking of the world’s poison at the ocean churning. It is offered to no other deity.', science: 'Datura is genuinely toxic — the offering is symbolic and never ingested; the tradition encodes respect for a dangerous plant by assigning it to the one God beyond harm.' },
      { item: 'Akanda / Aak (Crown flower)', dev: 'आक का फूल', role: 'The pale crown-flower offered to Shiva and Hanuman.', traditional: 'Aak is a wild, unsought flower — Shiva, the ascetic, loves what the world overlooks; its garlands are also placed on Hanuman.', science: 'Calotropis is a hardy desert plant available where garden flowers are not — making worship possible everywhere; its latex is irritant, handled with care.' },
      { item: 'Marigold (Genda)', dev: 'गेंदा', role: 'The orange-yellow garland flower of festivals, doors and deities.', traditional: 'Its sun-colours are auspicious and its endurance through the day makes it the festival garland; torans of marigold welcome the gods at the door.', science: 'Marigolds stay fresh far longer than most flowers and their pungency repels insects from doorways — practical decoration.' },
      { item: 'Lotus', dev: 'कमल', role: 'The flower of Lakshmi and of Vishnu’s feet.', traditional: 'The lotus rises unstained from mud — the symbol of a pure life amid the world; Lakshmi sits upon it and Vishnu holds it. Offering a lotus is offering purity itself.', science: 'The lotus leaf’s famous self-cleaning surface (micro-texture sheds dirt) is the physical marvel behind the ancient symbol.' },
      { item: 'Rose', dev: 'गुलाब', role: 'Red and pink roses offered to the Goddess and to Vishnu.', traditional: 'The rose is the queen of fragrance; the Goddess, who is beauty and abundance, is worshipped with the most beautiful flower available.', science: 'Rose petals are edible and safe for prasad-adjacent use; their scent is the classic calming fragrance.' },
      { item: 'Harsingar / Parijat (Night jasmine)', dev: 'हरसिंगार', role: 'Orange-stemmed night flowers offered to Vishnu and Krishna, gathered at dawn.', traditional: 'Parijat is the celestial tree Krishna brought from heaven for Satyabhama; its flowers fall at night, so they are gathered at dawn like a gift fallen from the sky.', science: 'The flowers bloom and drop in one night, so daily dawn collection made them a discipline of early rising.' },
      { item: 'Mango leaves (Aam ke patte)', dev: 'आम के पत्ते', role: 'Strung as toran at doors and arranged on the kalash mouth.', traditional: 'Mango is the kalpavriksha of the household — ever-green leaves at the threshold invite auspiciousness and mark a home in celebration; on the kalash they are the hair of the deity-pot.', science: 'Mango leaves stay green for days without water and release mild antimicrobial volatiles — a hygienic, long-lasting door decoration.' },
      { item: 'Banana (fruit & leaf)', dev: 'केला', role: 'Fruit offered in nearly every bhog; leaves used as the deity’s plate in South Indian and festive puja.', traditional: 'The banana is called the fruit of the sages; its plant is worshipped on Thursdays as Brihaspati’s own. The whole plant — fruit, leaf, stem — serves the puja.', science: 'Banana is an instant-energy fruit that peels hygienically; the leaf is a natural, disposable, slightly antiseptic plate.' },
      { item: 'Kusha grass', dev: 'कुशा', role: 'Sacred grass used in Vedic rites, pitru tarpan and sankalp.', traditional: 'Kusha sprang from Vishnu’s own body in the Samudra Manthan telling; rings and mats of kusha purify the seat of the ritual and the hands that give tarpan.', science: 'Kusha (Desmostachya) blades are tough and long-lasting when dried, forming clean, reusable ritual mats and rings.' }
    ]
  },
  {
    id: 'textiles-threads',
    title: 'Textiles & Threads',
    dev: 'वस्त्र और सूत्र',
    items: [
      { item: 'Moli / Kalava (Red sacred thread)', dev: 'मोली / कलावा', role: 'Red-yellow thread tied on the wrist at every puja and around the kalash.', traditional: 'The moli is the band of protection (raksha sutra) — tied with a mantra it seals the blessing of the puja onto the wearer; on the kalash it binds the invoked deity to the pot.', science: 'A wrist band is a durable, visible reminder of the vow taken; the practice keeps the sankalp present to the mind through the day.' },
      { item: 'Red cloth', dev: 'लाल वस्त्र', role: 'Cloth spread on the chowki and wrapped around the kalash coconut and Goddess murtis.', traditional: 'Red is the colour of the Goddess, of shakti, of auspicious beginnings; the deity is seated on red as a bride is seated on red.', science: 'Red dyes (traditionally madder/lac) were the most colourfast natural dyes — red cloth stayed bright through festival use.' },
      { item: 'Yellow cloth', dev: 'पीला वस्त्र', role: 'Cloth used for Vishnu, Satyanarayan and Guru puja platforms.', traditional: 'Yellow is Vishnu’s colour (pitambar) and Jupiter’s; it stands for knowledge, turmeric-purity and spring.', science: 'Yellow was dyed with turmeric — itself antiseptic — so yellow ritual cloths were the cleanest textiles in the house.' },
      { item: 'Chunri', dev: 'चुनरी', role: 'The decorated red veil offered to the Goddess and draped on Her murti.', traditional: 'Offering a chunri is offering clothing to the Mother as a daughter or son would; the Goddess in red chunri is the image of shakti honoured.', science: 'A new cloth gift in temple tradition circulated quality textiles into community redistribution as prasad.' },
      { item: 'Janeyu (Sacred thread)', dev: 'जनेऊ', role: 'The cotton thread worn by the initiated and offered to murtis of Ganesh and Vishnu.', traditional: 'Its three strands stand for debts to the gods, the sages and the ancestors — and for body, speech and mind kept in discipline.', science: 'Spun raw cotton is the simplest undyed textile — historically the cleanest thing worn against the skin.' }
    ]
  },
  {
    id: 'metals-vessels',
    title: 'Metals & Vessels',
    dev: 'धातु और पात्र',
    items: [
      { item: 'Kalash', dev: 'कलश', role: 'The water-filled pot, crowned with leaves and a coconut, that anchors every puja.', traditional: 'The kalash is the deity in pot form — its water is the cosmic ocean, the leaves the living world, the coconut the divine head; invoking the gods into the kalash makes the puja’s presence tangible.', science: 'A covered copper or steel pot of water keeps the ritual water fresh and symbolically centralises the rite in one clean vessel.' },
      { item: 'Lota / Achamani', dev: 'लोटा / आचमनी', role: 'Small water vessel and spoon for offering and ritual sipping.', traditional: 'Water offered with the achamani spoon purifies the offerer between each act; the small measure keeps the mind precise and unhurried.', science: 'Measured small pours are hygienic — no fingers touch the shared water.' },
      { item: 'Copper vessel', dev: 'ताँबे का पात्र', role: 'Preferred metal for puja water and kalash.', traditional: 'Copper is the metal of Surya and of purity; water kept in copper overnight is the traditional morning drink of health (tamra jal).', science: 'Copper has the well-documented oligodynamic effect — water stored in copper vessels shows reduced microbial load.' },
      { item: 'Thali (Puja plate)', dev: 'पूजा की थाली', role: 'The plate that carries diya, akshat, flowers, sweets and water in aarti.', traditional: 'The thali gathers the five-element offering in one circle; circling it before the deity returns the cosmos’ gifts to their source.', science: 'A single plate keeps the ritual compact and prevents offerings scattering onto the floor.' },
      { item: 'Ghanta (Bell)', dev: 'घंटा', role: 'Rung at the start of puja, during aarti and at katha chapter-ends.', traditional: 'The bell’s sound is Om made audible; it is rung to invite the deity, to dismiss disturbing influences, and to gather the worshipper’s scattered attention into the moment.', science: 'A clear bell tone cuts through ambient noise and instantly focuses the hearing mind — a practical attention-reset before prayer.' },
      { item: 'Shankh (Conch)', dev: 'शंख', role: 'Blown at aarti and kept filled with water for abhishek.', traditional: 'The conch is Vishnu’s own, producing the primordial sound; its water (shankh-jal) is among the purest offerings, and its blast announces the sacred hour.', science: 'The conch’s resonance vibrates at deep chest frequencies; blowing it is a full-breath exercise, and the sound carries across a village.' },
      { item: 'Panchapradeep / Aarti lamp', dev: 'पंचप्रदीप', role: 'The multi-wick lamp waved in formal aarti.', traditional: 'Five flames stand for the five elements offered together; waving the lamp in circles before the deity is the core gesture of aarti — offering light to the Light.', science: 'Multiple wicks give a broad bright flame visible to a whole gathered crowd at once.' }
    ]
  },
  {
    id: 'grains-seeds-misc',
    title: 'Grains, Seeds & Other Essentials',
    dev: 'अनाज और अन्य',
    items: [
      { item: 'Navadhanya (Nine grains)', dev: 'नवधान्य', role: 'The nine grains placed under the kalash or in the puja mound.', traditional: 'Each grain belongs to one of the nine planets (navagraha) — wheat to the Sun, rice to the Moon, and so on; placing all nine invokes the whole celestial order into the rite.', science: 'A seed-mix of nine grains is a compressed symbol of food security — the household’s entire harvest offered first to God.' },
      { item: 'Til (Sesame)', dev: 'तिल', role: 'Black and white sesame offered in havan, sankranti sweets and tarpan.', traditional: 'Til is born of Vishnu’s sweat in the telling and destroys darkness; til-gul on Makar Sankranti carries the blessing “speak sweetly”. Black til is offered to Shani and to the ancestors.', science: 'Sesame is warming, iron-rich winter food — the Sankranti timing matches the coldest season’s dietary need.' },
      { item: 'Jau (Barley)', dev: 'जौ', role: 'Barley grains sown for Navratri (jawara) and used in havan.', traditional: 'The sprouting barley of Navratri is the Goddess’s own growth in the home; its green shoots on the ninth day measure the household’s blessing.', science: 'Barley sprouts quickly and evenly, making it the practical choice for a living nine-day ritual indicator.' },
      { item: 'Laung & Elaichi (Clove & Cardamom)', dev: 'लौंग और इलायची', role: 'Spices offered with paan and placed in prasad.', traditional: 'The most fragrant spices complete the deity’s meal; a clove pair is also the traditional carrier of a wish tucked into the offering.', science: 'Both are strong natural antiseptics and mouth-fresheners; they keep dry prasad aromatic for days.' },
      { item: 'Gangajal', dev: 'गंगाजल', role: 'Water of the Ganga sprinkled to purify spaces, people and offerings.', traditional: 'Ganga is the Goddess who descended to earth through Shiva’s hair; her water purifies wherever it touches and no Hindu rite of sanctification is complete without it.', science: 'Ganga water famously keeps long without foul smell — historically attributed to its oxygenation and bacteriophage content — making it the natural choice for stored holy water.' },
      { item: 'Dakshina (Coins)', dev: 'दक्षिणा', role: 'Money offered to the deity, the pandit and the elders after puja.', traditional: 'Dakshina completes the yajna — the act of giving seals the act of receiving; the coin in the kalash and the gift to the priest keep the circle of generosity moving.', science: 'Ritualised giving redistributed resources through the community — the practical social function beneath the sacred form.' },
      { item: 'Havan samagri', dev: 'हवन सामग्री', role: 'The blend of herbs, grains and woods poured into the sacred fire.', traditional: 'Agni is the mouth of the gods in Vedic thought — what is given into fire reaches heaven; the samagri is the complete vegetarian oblation of grains, ghee and herbs.', science: 'Havan smoke from ghee, medicinal woods and herbs was a traditional fumigation of the home; it fragrances and clears closed winter rooms.' },
      { item: 'Panchgavya', dev: 'पंचगव्य', role: 'The five products of the cow (milk, curd, ghee, gomutra, gobar) mixed for purification.', traditional: 'The cow is the mother of nourishment; her five gifts together purify spaces and, in Ayurvedic tradition, the body itself.', science: 'The fermented milk components are probiotic; gobar-based floor pasting was the traditional hygienic, antiseptic flooring of rural homes.' }
    ]
  }
];

function whyFind(query) {
  const words = query.toLowerCase().split(/\s+/).filter(w => w.length > 2 && !['why','what','the','use','used','offer','offered','does','for','and','are','with','puja'].includes(w));
  const hits = [];
  WHY_CATEGORIES.forEach(c => c.items.forEach(it => {
    let score = 0;
    const name = (it.item + ' ' + it.dev).toLowerCase();
    const body = (it.role + ' ' + it.traditional + ' ' + it.science + ' ' + c.title).toLowerCase();
    words.forEach(w => {
      if (name.includes(w)) score += 10;
      else if (body.includes(w)) score += 1;
    });
    if (score > 0) hits.push({ it, score });
  }));
  hits.sort((a, b) => b.score - a.score);
  return hits.map(h => h.it);
}
